/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";
import type { DrizzleToZeroSchema, ZeroCustomType } from "drizzle-zero";
import type * as drizzleSchema from "./db/schema/public";

type ZeroSchema = DrizzleToZeroSchema<typeof drizzleSchema>;

/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    budget: {
      name: "budget",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "budget",
            "id"
          >,
        },
        orgId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "budget",
            "orgId"
          >,
          serverName: "org_id",
        },
        label: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "budget",
            "label"
          >,
        },
        createdBy: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "budget",
            "createdBy"
          >,
          serverName: "created_by",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "budget",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "budget",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    category: {
      name: "category",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "category",
            "id"
          >,
        },
        budgetId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "category",
            "budgetId"
          >,
          serverName: "budget_id",
        },
        amount: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "category",
            "amount"
          >,
        },
        every: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "category",
            "every"
          >,
        },
        order: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "category",
            "order"
          >,
        },
        label: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "category",
            "label"
          >,
        },
        color: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "category",
            "color"
          >,
        },
        createdBy: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "category",
            "createdBy"
          >,
          serverName: "created_by",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "category",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "category",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
        removedBy: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "category",
            "removedBy"
          >,
          serverName: "removed_by",
        },
        removedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "category",
            "removedAt"
          >,
          serverName: "removed_at",
        },
      },
      primaryKey: ["id"],
    },
    plaidAccessTokens: {
      name: "plaidAccessTokens",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "plaidAccessTokens",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "plaidAccessTokens",
            "name"
          >,
        },
        logoUrl: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "plaidAccessTokens",
            "logoUrl"
          >,
        },
        userId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "plaidAccessTokens",
            "userId"
          >,
          serverName: "user_id",
        },
        token: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "plaidAccessTokens",
            "token"
          >,
        },
        syncCursor: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "plaidAccessTokens",
            "syncCursor"
          >,
          serverName: "sync_cursor",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "plaidAccessTokens",
            "createdAt"
          >,
          serverName: "created_at",
        },
      },
      primaryKey: ["id"],
      serverName: "plaidAccessToken",
    },
    plaidAccounts: {
      name: "plaidAccounts",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "plaidAccounts",
            "id"
          >,
        },
        user_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "plaidAccounts",
            "user_id"
          >,
        },
        token_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "plaidAccounts",
            "token_id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "plaidAccounts",
            "name"
          >,
        },
        type: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "plaidAccounts",
            "type"
          >,
        },
        mask: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "plaidAccounts",
            "mask"
          >,
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "plaidAccounts",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "plaidAccounts",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    plaidLink: {
      name: "plaidLink",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "plaidLink",
            "id"
          >,
        },
        user_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "plaidLink",
            "user_id"
          >,
        },
        link: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "plaidLink",
            "link"
          >,
        },
        token: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "plaidLink",
            "token"
          >,
        },
        completeAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "plaidLink",
            "completeAt"
          >,
          serverName: "complete_at",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "plaidLink",
            "createdAt"
          >,
          serverName: "created_at",
        },
      },
      primaryKey: ["id"],
    },
    transaction: {
      name: "transaction",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "transaction",
            "id"
          >,
        },
        user_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "transaction",
            "user_id"
          >,
        },
        account_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "transaction",
            "account_id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "transaction",
            "name"
          >,
        },
        amount: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "transaction",
            "amount"
          >,
        },
        datetime: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "transaction",
            "datetime"
          >,
        },
        authorized_datetime: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "transaction",
            "authorized_datetime"
          >,
        },
        json: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "transaction",
            "json"
          >,
        },
        category_id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "transaction",
            "category_id"
          >,
        },
        category_assigned_by: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "transaction",
            "category_assigned_by"
          >,
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "transaction",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "transaction",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    users: {
      name: "users",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "name"
          >,
        },
        email: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "email"
          >,
        },
        emailVerified: {
          type: "boolean",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "emailVerified"
          >,
          serverName: "email_verified",
        },
        image: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "image"
          >,
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
      serverName: "user",
    },
  },
  relationships: {
    plaidAccounts: {
      transaction: [
        {
          sourceField: ["id"],
          destField: ["account_id"],
          destSchema: "transaction",
          cardinality: "many",
        },
      ],
    },
    budget: {
      categories: [
        {
          sourceField: ["id"],
          destField: ["budgetId"],
          destSchema: "category",
          cardinality: "many",
        },
      ],
    },
    category: {
      budget: [
        {
          sourceField: ["budgetId"],
          destField: ["id"],
          destSchema: "budget",
          cardinality: "one",
        },
      ],
      transactions: [
        {
          sourceField: ["id"],
          destField: ["category_id"],
          destSchema: "transaction",
          cardinality: "many",
        },
      ],
    },
    transaction: {
      account: [
        {
          sourceField: ["account_id"],
          destField: ["id"],
          destSchema: "plaidAccounts",
          cardinality: "one",
        },
      ],
      category: [
        {
          sourceField: ["category_id"],
          destField: ["id"],
          destSchema: "category",
          cardinality: "one",
        },
      ],
    },
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "budget" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Budget = Row<Schema["tables"]["budget"]>;
/**
 * Represents a row from the "category" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Category = Row<Schema["tables"]["category"]>;
/**
 * Represents a row from the "plaidAccessTokens" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type PlaidAccessToken = Row<Schema["tables"]["plaidAccessTokens"]>;
/**
 * Represents a row from the "plaidAccounts" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type PlaidAccount = Row<Schema["tables"]["plaidAccounts"]>;
/**
 * Represents a row from the "plaidLink" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type PlaidLink = Row<Schema["tables"]["plaidLink"]>;
/**
 * Represents a row from the "transaction" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Transaction = Row<Schema["tables"]["transaction"]>;
/**
 * Represents a row from the "users" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<Schema["tables"]["users"]>;

/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = createBuilder(schema);
