/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";
import type { CustomType } from "drizzle-zero";
import type * as drizzleSchema from "./db/schema/public";

/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    balance: {
      name: "balance",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "balance",
            "id"
          >,
        },
        user_id: {
          type: "string",
          optional: false,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "balance",
            "user_id"
          >,
          serverName: "userId",
        },
        plaid_id: {
          type: "string",
          optional: false,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "balance",
            "plaid_id"
          >,
          serverName: "plaidId",
        },
        avaliable: {
          type: "number",
          optional: false,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "balance",
            "avaliable"
          >,
        },
        current: {
          type: "number",
          optional: false,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "balance",
            "current"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "balance",
            "name"
          >,
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "balance",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "balance",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    plaidLink: {
      name: "plaidLink",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "plaidLink",
            "id"
          >,
        },
        user_id: {
          type: "string",
          optional: false,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "plaidLink",
            "user_id"
          >,
        },
        link: {
          type: "string",
          optional: false,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "plaidLink",
            "link"
          >,
        },
        token: {
          type: "string",
          optional: false,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "plaidLink",
            "token"
          >,
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "plaidLink",
            "createdAt"
          >,
          serverName: "created_at",
        },
      },
      primaryKey: ["id"],
    },
    transaction: {
      name: "transaction",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "transaction",
            "id"
          >,
        },
        user_id: {
          type: "string",
          optional: false,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "transaction",
            "user_id"
          >,
        },
        plaid_id: {
          type: "string",
          optional: false,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "transaction",
            "plaid_id"
          >,
        },
        account_id: {
          type: "string",
          optional: false,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "transaction",
            "account_id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "transaction",
            "name"
          >,
        },
        amount: {
          type: "number",
          optional: false,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "transaction",
            "amount"
          >,
        },
        datetime: {
          type: "number",
          optional: true,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "transaction",
            "datetime"
          >,
        },
        authorized_datetime: {
          type: "number",
          optional: true,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "transaction",
            "authorized_datetime"
          >,
        },
        json: {
          type: "string",
          optional: true,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "transaction",
            "json"
          >,
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "transaction",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "transaction",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    users: {
      name: "users",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "users",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: true,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "users",
            "name"
          >,
        },
        email: {
          type: "string",
          optional: false,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "users",
            "email"
          >,
        },
        emailVerified: {
          type: "boolean",
          optional: true,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "users",
            "emailVerified"
          >,
          serverName: "email_verified",
        },
        image: {
          type: "string",
          optional: true,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "users",
            "image"
          >,
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "users",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as CustomType<
            typeof drizzleSchema,
            "users",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
      serverName: "user",
    },
  },
  relationships: {},
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "balance" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Balance = Row<Schema["tables"]["balance"]>;
/**
 * Represents a row from the "plaidLink" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type PlaidLink = Row<Schema["tables"]["plaidLink"]>;
/**
 * Represents a row from the "transaction" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Transaction = Row<Schema["tables"]["transaction"]>;
/**
 * Represents a row from the "users" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<Schema["tables"]["users"]>;

/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = createBuilder(schema);
